### PR TITLE
Drop the Generic prefix

### PR DESCRIPTION
**Pull request by bergmark**
How about renaming these? I'm tired of writing Generics.Generic :-)

### CODE REVIEW

**Comment by hesselink** [comment]
Just copy it :) But in general, this seems to be the convention in generic programming libraries: `Generics.<name of library/approach>.<implemented thing>`. So there's `Generics.Regular.Foo`, `Generics.SYB.Bar`, `Generics.SOP.Baz` etc. Also it would break all the code using it.

**Comment by hesselink** [comment]
In general I like two level namespaces though. If we'd be starting from scratch, I'd probably go for `Generic.Aeson`.

**Comment by bergmark** [comment]
But do any of the GHC Generics libraries do this? uniplate is Data.Generics.Uniplate, generics-deriving is Generics.Deriving

**Comment by hesselink** [comment]
Neither of those use GHC Generics, they're both different mechanisms, and
they kinda follow the same scheme, except for uniplate which adds an extra
'Data'. It seems the generic-deriving now does GHC generics, but that's a
recent thing and the name is from before.

**Comment by bergmark** [comment]
You seem to have stronger opinions on this than i do so i'll concede :-)

**Comment by hesselink** [comment]
I don't feel super strongly about this, but I don't really think the benefits are huge and it would break all code using it.

**Pull request closed without merging**
