### PR TITLE
Update for GHC 9.0

### PR DESCRIPTION
**Pull request by serras**
I've tested that this works on GHC 8.10.4 and 9.0.1.

### CODE REVIEW

**Comment by bergmark** [comment]
Thanks! I'll make a release

**Comment by hesselink** [comment]
It looks like `Type` has been in base for a long time, so we could probably just switch here and not have the CPP?

**Comment by serras** [comment]
Sure, I can prepare a PR for that if you prefer. I did it in this way because I was not sure how many GHC versions you wanted to support.

**Comment by bergmark** [comment]
dropping ghc 7 support sounds good to me, otherwise cpp can probably be avoided with base-compt

**Comment by serras** [comment]
Unfortunately it seems that `base-compat` does not have a `Data.Kind` module :(

**Comment by bergmark** [comment]
oh interesting. maybe too old to be a prio for them as well :-)

**Pull request merged**
