### PR TITLE
Compile with stackage lts-13.13

### PR DESCRIPTION
**Pull request by enobayram**

### CODE REVIEW

**Comment by hesselink** [comment]
Thanks for this, happy to merge, however it seems to fail CI. It would be great if you could check and possibly fix that.

**Comment by enobayram** [comment]
@hesselink No problem. I'm glad the CI failed, because the fix is much better than my original commit.

**Comment by hesselink** [comment]
Thanks! I'll try to make a release tonight.

**Comment by hesselink** [comment]
In fact I made one now :) Released as 0.2.0.10

**Comment by enobayram** [comment]
That's great, thanks a lot! I'll depend on the hackage version now :)

**Pull request merged**
